# Mods.toml for the omnixerio_devices mod by ultreon (originally created my MrCrayfish)
# Copyright (c) 2022 - Ultreon Team, GPLv3 License. See the license at https://www.gnu.org/licenses/gpl-3.0-standalone.html

modLoader = "javafml"
loaderVersion = "[1,)"
license = "GPL-3.0"
issueTrackerURL = "https://github.com/omnixerio/omnixerio_devices-mod/issues"

# The main mod, and all sub-mods.
[[mods]]
modId = "omnixerio_devices"
version = "${version}"
displayName = "Omnixerio omnixerio_devices"
#updateJSONURL="http://myurl.me/"
displayURL = "https://github.com/omnixerio/omnixerio-devices"
logoFile = "omnixerio_devices.png"
credits = "Thanks to MrCrayfish for the idea and the original mod that was made in 1.12.2. Thank you to MinecraftDoodler for helping with textures. Thank you to lizterzapzap for the omnixerio_devices Mod icon. Cheers to these people for donating during the development: Mastef Chief, Haunted Corpse, Jake Crowley, fabbe50, PlayDashGaming, jack jook, Hunstagamez, Techyy YT, MinecraftDoodler, Norge100YT, Cyberman2208, CreepergamingsMC"
authors = "Qboi123, Jab125"
description = """
Adds working electronic omnixerio_devices into Minecraft!
CurseForge: https://curseforge.com/minecraft/mc-mods/omnixerio_devices-mod
Modrinth: https://modrinth.com/mod/omnixerio_devices-mod
Source Code: https://github.com/omnixerio/omnixerio_devices-mod

Original mod made by MrCrayfish called "MrCrayfish's Device Mod".
Available at: https://mrcrayfish.com/mods/cdm
Source Code: https://github.com/MrCrayfish/MrCrayfishDeviceMod
"""
itemIcon = "omnixerio_devices:red_laptop"

[[mixins]]
config = "omnixerio-devices.mixins.json"
[[mixins]]
config = "omnixerio-devices-common.mixins.json"

# Dependencies for the main mod.
[[dependencies.omnixerio_devices]]
modId = "neoforge"
mandatory = true
versionRange = "[26.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.omnixerio_devices]]
modId = "minecraft"
mandatory = true
versionRange = "26.2"
ordering = "NONE"
side = "BOTH"

[[dependencies.omnixerio_devices]]
modId = "architectury"
mandatory = true
versionRange = "[21,22)"
ordering = "NONE"
side = "BOTH"
